on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: setup-flutter
      uses: takuyaohashi/setup-flutter@v1
      with:
        flutter-version: 'v1.16.3'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --debug --split-per-abi
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: pangolin-desktop
        # Directory containing files to upload
        path: build/app/outputs/apk/debug
